# The URL the site will be built for
base_url = "https://edwardtan.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The site theme to use.
theme = "particle-zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

# Site settings
description = "Edward Tan's personal website"

# User settings
username = "Edward Tan "
user_description = "Playing with Rust"
user_title = ""
email = "guofoo@gmail.com"
twitter_username = "guofoo"
github_username = "guofoo"
# gplus_username = "lorem_ipsum"